FROM php:8.3-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql exif

RUN pecl install redis && docker-php-ext-enable redis

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN mkdir -p storage/framework/views \
    storage/framework/cache \
    storage/framework/sessions \
    storage/logs

RUN chown -R www-data:www-data storage bootstrap/cache

RUN chmod +x /var/www/docker/php/entrypoint.sh

ENTRYPOINT ["docker/php/entrypoint.sh"]

CMD ["php-fpm"]